name: zhi_duo_duo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  provider: ^6.1.4
  auto_route: ^10.0.1
  global_configuration: ^2.0.0
  logger: ^2.5.0
  http: ^1.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2 
  cloud_firestore: ^5.6.6
  image_picker: ^1.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/images/
